---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: better-minecraft-world
  labels:
    app: better-minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi